### ISSUE TITLE
Issue on updating plugin

### ISSUE THREAD

**Issue by mikededo** [blackjid/plugin-kubectl#5]
Hi! 

I'm having the following error when updating the plugin: `fish: Unknown command: __kubectl.reset`.

Is there any solution? Tried installing and uninstalling (with fisher) and did not find any solution.

**Comment by blackjid** [comment]
Hi!, did you figure it out? sorry I missed the issue before..

**Comment by mikededo** [comment]
Hi! Nop, I just don't have to use it anymore and I was cleaning my inbox 😄
